Initialise Routes
MyLlama/EmployeeApp pull request #2
Opened 2023-10-23 12:58 UTC by himanshm

Add user authentication store
Add markup for user to submit a form to authenticate them Changes to be committed:
	modified:   .gitignore
	modified:   package-lock.json
	modified:   package.json
	new file:   src/components/layout/TheHeader.vue
	modified:   src/main.ts
	modified:   src/router/index.ts
	new file:   src/stores/auth.ts
	new file:   src/views/users/TheLogin.vue

2023-10-23 15:32 UTC, disha1202 requested changes

2023-10-23 15:32 UTC, disha1202 commented on src/views/users/TheLogin.vue
> +  console.log('Form Submitted!')
remove console log

2023-10-23 15:32 UTC, disha1202 commented on src/views/users/TheLogin.vue
> +    <div>
Use vuetify components

2023-10-26 06:23 UTC, AishwaryShrivastav commented on src/main.ts
> +const vuetify = createVuetify({
please move it after import

2023-10-26 06:23 UTC, merged