Login design
MyLlama/EmployeeApp pull request #5
Opened 2023-10-25 19:03 UTC by himanshm

Initial Design of Login Page
Add design to the login page
Change auth store to compositon api
import vuetify library and its components
Change directory name of TheLogin.vue file

2023-10-26 06:02 UTC, disha1202 requested changes

2023-10-26 06:02 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +import loginImg from '../../assets/identity.svg'
Why don't we create an svg folder img inside assets and keep all the svgs over there.

2023-10-26 06:33 UTC, AishwaryShrivastav commented on src/assets/identity.svg
rename the file with proper name

2023-10-26 06:33 UTC, AishwaryShrivastav commented on src/stores/auth.ts
> +// export const useAuthStore = defineStore({
remove commented code if its not for future use

2023-10-27 07:08 UTC, himanshm commented on src/views/auth/TheLogin.vue
> +    // Use replace to not enable the user to return to login route
Implementing this in next PR

2023-10-27 10:32 UTC, disha1202 requested changes

2023-10-27 10:32 UTC, disha1202 commented on src/stores/auth.ts
> +export function useAuthStore() {
Use defineStore

2023-10-27 18:21 UTC, himanshm commented on src/stores/auth.ts
> +export function useAuthStore() {
Done!

2023-10-30 05:14 UTC, disha1202 requested changes

2023-10-30 05:14 UTC, disha1202 commented on src/App.vue
> +const isHomePage = computed(() => route.path === '/home')
We need to display side bar and bottom navigation on all the pages except for login. 
Not just on home page.

2023-10-30 05:14 UTC, disha1202 commented on src/assets/images/logo.svg
Remove this file

2023-10-30 05:40 UTC, disha1202 requested changes

2023-10-30 05:40 UTC, disha1202 commented on src/stores/auth.ts
> +  const didAutoLogout = ref(false)
Why do we need this variable?

2023-10-30 05:40 UTC, disha1202 commented on src/stores/auth.ts
> +  const tokenExpiry = useStorage('tokenExpirey', 0)
Improve variable name

2023-10-30 05:40 UTC, disha1202 commented on src/stores/auth.ts
> +      // const expiresIn = 5000 // Testing
Remove commented code

2023-10-30 05:45 UTC, disha1202 requested changes

2023-10-30 05:45 UTC, disha1202 commented on src/router/index.ts
> +})
Remove meta property and improve logic for routing guards

2023-10-30 05:53 UTC, disha1202 commented
Resolve conflicts

2023-10-30 06:41 UTC, disha1202 requested changes

2023-10-30 06:41 UTC, disha1202 commented on src/stores/auth.ts
> +  }
```suggestion
   return !!authToken.value
  }
```

2023-10-30 07:24 UTC, disha1202 requested changes

2023-10-30 07:24 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +                    ></i>
```suggestion
                    <i
                      :class=`isax ${showPassword ? 'isax-eye' : 'isax-eye-slash' } pointer`
                      v-if="showPassword"
                      @click="showPassword = !showPassword"
                    >
                    </i>
                    
```

2023-10-30 07:48 UTC, himanshm commented on src/stores/auth.ts
> +  const tokenExpiry = useStorage('tokenExpirey', 0)
changed it to validityDuration

2023-10-30 08:32 UTC, disha1202 requested changes

2023-10-30 08:32 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +                  class="input-fields"
Remove this class

2023-10-30 08:32 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +                    class="checkbox"
Remove this class

2023-10-30 08:32 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +                <p v-if="!loginIsValid">Please enter your username and password!</p>
Why is this needed?

2023-10-30 08:52 UTC, himanshm commented on src/views/auth/TheLogin.vue
> +                <p v-if="!loginIsValid">Please enter your username and password!</p>
Removed!

2023-10-30 09:12 UTC, disha1202 requested changes

2023-10-30 09:12 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +}
Remove this

2023-10-30 09:12 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +  validateLogin()
Remove this

2023-10-30 09:12 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +  await authStore.userLogin(username.value, password.value, router)
Check if username and password is there, only then make api call.

2023-10-30 09:12 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +    snackbar.value = true // Show snackbar when authentication fails
Improve variable name

2023-10-30 09:18 UTC, himanshm commented on src/views/auth/TheLogin.vue
> +                    class="checkbox"
Done!

2023-10-30 09:28 UTC, himanshm commented on src/views/auth/TheLogin.vue
> +}
Done!

2023-10-30 09:29 UTC, himanshm commented on src/views/auth/TheLogin.vue
> +  validateLogin()
Removed!

2023-10-30 09:31 UTC, himanshm commented on src/views/auth/TheLogin.vue
> +    snackbar.value = true // Show snackbar when authentication fails
Made it showSnackbar

2023-10-30 09:56 UTC, disha1202 requested changes

2023-10-30 09:56 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +    <div class="text-center">
Remove this class

2023-10-30 09:56 UTC, disha1202 commented on src/views/auth/TheLogin.vue
> +        Invalid Credentials
Internationalize text

2023-10-30 10:02 UTC, disha1202 approved these changes
LGTM 👍🏻

2023-10-31 06:29 UTC, merged